name: CI

on: [push, pull_request]

jobs:
  lint-and-smoketest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt ruff black
      - name: Lint
        run: |
          ruff src
          black --check src
      - name: Smoke test import
        run: |
          python - <<'PY'
import importlib
importlib.import_module("src.spotify_playlist_optimizer")
print("Import OK")
PY
